name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    
jobs:
  build:
    name: Publishing GeneeUI yo NPMJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install  
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      - run: npm config set username=${{secrets.$NPM_USERNAME}}
      - run: npm config set password=${{secrets.NPM_PASSWORD}}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
